name: AdsInAdChat
version: ${project.version}
main: me.hsgamer.adsinadchat.AdsInAdChat
api-version: 1.13
authors: [ HSGamer ]
description: Change ad text to ad links

permissions:
  aiac.bypass:
    description: Bypass the triggers
    default: op